[build]
  command = "npm --prefix ../backend install --include=dev && npm install --include=dev && npm run build"
  publish = ".next"
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/api/v1/*"
  to = "/.netlify/functions/api/api/v1/:splat"
  status = 200
  force = true
