[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/v1/*"
  to = "/.netlify/functions/api/api/v1/:splat"
  status = 200
  force = true
